site_name: Libejovopp

site_description: High level API for libejovopp
site_author: Evan Voyles

# repo_url: https://github.com/ejovo13/libejovopp

theme:
  # name: mkdocs
  name: readthedocs
  # nav_style: dark
  hljs_style: monokai
